- name: play level variables
  hosts: localhost
  vars: #play level variable 
    COURSE: AWS 
    TRAINER: siva 
    TIME: 120 
  tasks:
    - name: play level variables  
      ansible.builtin.debug: 
      vars:  
        COURSE: Ansible 
        TRAINER: kedarnath 
        TIME: 15 days
        msg:  "hello we are learning {{COURSE}}, Trainer is {{TRAINER}} & duration is {{TIME}} hrs"

    - name: tasks level variables 
      anisible.buitin.debug: 
        msg:  "hello we are learning {{COURSE}}, Trainer is {{TRAINER}} & duration is {{TIME}} hrs"


