- name: play level variables
  hosts: localhost
  vars: #play level variable 
    COURSE: AWS 
    TRAINER: siva 
    TIME: 120 
  tasks:
    - name: play level variables 
      vars: 
        COURSE: "ansible"
        TIME: "15 days"
        TRAINER: "kedarnath"
      ansible.builtin.debug:
        msg: "we are learning {{COURSE}}, Trainer is {{TRAINER}} & duration is {{TIME}}"
    - name: task level variables 
      ansible.builtin.debug:
        msg: "we are learning {{COURSE}}, Trainer is {{TRAINER}} & duration is {{TIME}}"