- name: variables from prompt 
  hosts: localhost
  vars_prompt:
   - name: TRAINER
     prompt: please enter the Trainer name
     private: no 

   - name: COURSE
     prompt: please enter the Trainer name
     private: yes 
   - name: TIME
     prompt: please enter the Trainer name
     private: no   
    
  tasks: 
    - name: prompt variables 
      ansible.builtin.debug:
       msg: hello we are learning {{COURSE}}, Trainer is {{TRAINER}} & duration is {{TIME}} hrs
       