- name: variables form files 
  hosts: localhost
  tasks:
    - name: variable from file 
      ansible.builtin.debug:
        msg: "hello we are learning {{COURSE}}, Trainer is {{TRAINER}} & duration is {{TIME}} hrs"  