- name: conditions when 
  hosts: web 
  become: yes 
  gather_facts: true 
  tasks: 
    - name: check the user is existed or not 
      ansible.builtin.command: id Expense 
      register: User_Expense
      ignore_errors: true  

    - name: printing the User info 
      ansible.builtin.debug:
        msg: "user info is {{User_Expense}}"

    - name: if not existed . you need to create 
      ansible.builtin.command: useradd Expense 
      when: User_Expense.rc != 0 

    - name: print the User_Expense statement 
      ansible.builtin.debug:
        msg: "hello am here"
    
