- name: mysql confiagaration 
  hosts: mysql
  vars:
   - mysql_passwd: ExpenseApp@1
  become: true 
  tasks:
    - name: install the mysql server-d 
      ansible.builtin.dnf:
        name: mysql-server
        state: present 
    - name: enable and start the mysql service 
      ansible.builtin.service:
        name: mysql-server
        state: started 
        enabled: yes 
    - name: cheking the password is settedup or not 
      community.mysql.mysql_user:
         login_user: root
         login_password: {{ mysql_passwd }}
         filter: version 
      ignore_errors: yes 
      register: mysql_connection_output 
    
    - name: printing the version info 
      ansible.builtin.debug:
        msg: {{ mysql_version }}
    
    - name: setting up the root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_passwd }}
      when: mysql_connection_output.failed is true 

      